### ISSUE TITLE
Fullscreen button or shortcut key?

### ISSUE THREAD

**Issue by ghost** [gilzoide/draw-over#2]
Hi, Gil
  Great work! Is there a fullscreen mode available? shortcut or hidden button?

**Comment by gilzoide** [comment]
Thanks!
There is no fullscreen mode right now, but it is really easy adding one.
I think the only problem with real fullscreen is that some desktops may not display other apps in the same screen, like how MacOS creates a new exclusive desktop for fullscreen apps, which kind of defeats the purpose of Draw Over.

Anyway, it is possible and a good idea to have this!
I was also thinking on having a toggle for window borders, so a maximized window would work like a fullscreen app, but without this limitation of desktops.
Then it should probably need some kind of border marker, since it is super easy to forget that the app is open if you can't see it at all and we'd try to interact with the app just below it and start drawing =P

Some desktops can toggle any app fullscreen, maybe yours can too, while this isn't builtin in the app (I can confirm it works wonderfully in KDE) =]

**Comment by ghost** [comment]
Yes. Using window manager to make Draw Over fullscreen is OK.
This kind of app is not as portable as normal one. It's desktop deps. 
Any way, Good work and keep going.
